// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated with protocol_gen.go -- do not edit this file.
//   go run scripts/protocol_gen/protocol_gen.go
//
// DAP version 1.65.0

#include "dap/protocol.h"

namespace dap 
{

   DAP_IMPLEMENT_STRUCT_TYPEINFO(InitializedEvent, "initialized");

   DAP_IMPLEMENT_STRUCT_TYPEINFO(StoppedEvent,
      "stopped",
      DAP_FIELD(allThreadsStopped, "allThreadsStopped"),
      DAP_FIELD(description, "description"),
      DAP_FIELD(hitBreakpointIds, "hitBreakpointIds"),
      DAP_FIELD(preserveFocusHint, "preserveFocusHint"),
      DAP_FIELD(reason, "reason"),
      DAP_FIELD(text, "text"),
      DAP_FIELD(threadId, "threadId"));

   DAP_IMPLEMENT_STRUCT_TYPEINFO(ThreadEvent,
      "thread",
      DAP_FIELD(reason, "reason"),
      DAP_FIELD(threadId, "threadId"));

}  // namespace dap
